# Generated by Django 3.2.5 on 2021-12-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Rack',
        ),
    ]
