# Generated by Django 3.2.5 on 2021-12-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_student_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, unique=True)),
                ('rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.location')),
                ('routers_id', models.IntegerField(unique=True)),
            ],
            bases=('backend.location',),
        ),
    ]
