# Generated by Django 3.2.7 on 2021-12-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipv4_network',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('ip_range', models.CharField(max_length=200)),
                ('ip_address', models.CharField(default='192.168.1.0', max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BatteryBackup',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_api_backend.location')),
                ('battery_id', models.IntegerField(unique=True)),
            ],
            bases=('first_api_backend.location',),
        ),
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_api_backend.location')),
                ('patchpanels_id', models.IntegerField(unique=True)),
                ('number_of_ports', models.IntegerField()),
            ],
            bases=('first_api_backend.location',),
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_api_backend.location')),
                ('routers_id', models.IntegerField(unique=True)),
            ],
            bases=('first_api_backend.location',),
        ),
        migrations.AddField(
            model_name='location',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_api_backend.location')),
                ('switchs_id', models.IntegerField(unique=True)),
                ('network_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.ipv4_network')),
                ('router_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.router')),
            ],
            bases=('first_api_backend.location',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_api_backend.location')),
                ('servers_id', models.IntegerField(unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('patch_panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.patchpanel')),
            ],
            bases=('first_api_backend.location',),
        ),
        migrations.AddField(
            model_name='patchpanel',
            name='switch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.switch'),
        ),
        migrations.CreateModel(
            name='NetworkInterfaceCard',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.ipv4_network', to_field='ip_address')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.server')),
            ],
        ),
    ]
