# Generated by Django 3.2.7 on 2021-12-18 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to=settings.AUTH_USER_MODEL),
        ),
    ]
