# Generated by Django 3.2.7 on 2021-12-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0002_rack_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='owner',
        ),
    ]
